### PR TITLE
Snapping mechanism notebook

### PR DESCRIPTION
**Pull request by ctcovington**

### CODE REVIEW

**Comment by ctcovington** [comment]
Don't merge yet -- I'll update further after core and core-python PRs go through

**Comment by Shoeboxam** [comment]
@ctcovington What is the state of this notebook? Happy to handle Smartnoise renaming ports or any other necessary lifting.

**Comment by ctcovington** [comment]
I think it's ready to go if you think it is. It's a bit sparse, but I can't think of anything else I'd add.

**Comment by raprasad** [comment]
Notebook work moved to an OpenDP library issue: https://github.com/opendp/opendp/issues/389

**Pull request closed without merging**
